apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-dynamic-pvc-fileshare
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: my-azurefile
  resources:
    requests:
      storage: 2Gi
