prometheus:
  url: http://mon-kube-prometheus-stack-prometheus.monitoring.svc
  port: 9090
logLevel: 10
rules:
  default: false
  custom:
  - seriesQuery: 'request_duration_seconds_bucket'
    name:
      matches: "request_duration_seconds_bucket"
      as: "my_custom_metric"      
    resources:
      overrides:
        namespace: {resource: "namespace"}
        pod: {resource: "pod"}
    metricsQuery: 'avg(request_duration_seconds_bucket{job="hpademometrics"})'