prometheus:
  url: http://mon-kube-prometheus-stack-prometheus.monitoring.svc
  port: 9090
logLevel: 10
rules:
  default: false
  custom:
  - seriesQuery: 'request_duration_seconds_bucket{name!="",container!="POD"}'
    name:
      matches: "request_duration_seconds_bucket"
      as: "my_custom_metric"      
    resources:
      overrides:
        kubernetes_namespace: {resource: "namespace"}
        kubernetes_pod_name: {resource: "pod"}
    metricsQuery: 'sum(rate(<<.Series>>{<<.LabelMatchers>>})) by (<<.GroupBy>>)'