prometheus:
  url: http://mon-kube-prometheus-stack-prometheus.monitoring.svc
  port: 9090
logLevel: 10
rbac:
  create: true
  useAuthReaderClusterRole: false
  externalMetrics:
    resources: ["*"]
  customMetrics:
    resources: ["*"]
rules:
  default: false
  custom:
  - seriesQuery: 'request_duration_seconds_bucket'
    name:
      matches: "request_duration_seconds_bucket"
      as: "my_custom_metric"      
    resources:
      overrides:
        job: {resource: "namespace"}
        queue: {resource: "service"}
    metricsQuery: 'avg(request_duration_seconds_bucket{job="hpademometrics"})'