prometheus:
  url: http://mon-kube-prometheus-stack-prometheus.monitoring.svc
  port: 9090
logLevel: 10
rules:
  default: false
  custom:
  - seriesQuery: 'request_duration_seconds_bucket'
    name:
      matches: "request_duration_seconds_bucket"
      as: "my_custom_metric"      
    resources:
      overrides:
        kubernetes_namespace: {resource: "namespace"}
        kubernetes_pod_name: {resource: "pod"}
    metricsQuery: rate(request_duration_seconds_sum[1m]) * 1000 / rate(request_duration_seconds_count[1m])
  - seriesQuery: 'http_requests_received_total'
    name:
      matches: "http_requests_received_total"
      as: "my_app_requests"      
    resources:
      overrides:
        kubernetes_namespace: {resource: "namespace"}
        kubernetes_pod_name: {resource: "pod"}
    metricsQuery: increase(http_requests_received_total[1m])    