apiVersion: v1
data:
  config.yaml: |
    rules:
    - seriesQuery: '{__name__=~"request_duration_seconds_.*",namespace!="",pod!=""}'
      resources:
        overrides:
          kubernetes_namespace:
            resource: namespace
          kubernetes_pod_name:
            resource: pod
      name:
        matches: "^(.*)"
        as: "request_duration_seconds_avg"
      metricsQuery: 1000 * (sum(rate(request_duration_seconds_sum[5m]) > 0) by (<<.GroupBy>>) / sum(rate(request_duration_seconds_count[5m]) > 0) by (<<.GroupBy>>))
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/component: metrics-adapter
    app.kubernetes.io/name: prometheus-adapter
    app.kubernetes.io/version: 0.11.2
  name: adapter-config
  namespace: monitoring
