apiVersion: v1
kind: ConfigMap
metadata:
  name: adapter-config
  namespace: monitoring
data:
  config.yaml: |-
    rules:
      custom:
      - seriesQuery: '{__name__=~"request_duration_seconds_.*",namespace!="",pod!=""}'
        resources:
          overrides:
            namespace:
              resource: namespace
            pod:
              resource: pod
        name:
          matches: ^(.*)
          as: "request_duration_seconds_avg"
        metricsQuery: 1000 * (sum(rate(request_duration_seconds_sum[5m]) > 0) by (<<.GroupBy>>) / sum(rate(request_duration_seconds_count[5m]) > 0) by (<<.GroupBy>>))