prometheus:
  prometheusSpec:
    serviceMonitorSelectorNilUsesHelmValues: false
    serviceMonitorSelector: {}
    additionalScrapeConfigs:
      - job_name: hpademometrics
        scrape_interval: 15s 
        scrape_timeout: 10s 
        metrics_path: /metrics  
        scheme: http  
        static_configs:  
        - targets: ['demoapi-service:8000']
          labels:
            namespace: 'monitoring'
            pod: 'my_custom_metric'