apiVersion: v1
kind: PersistentVolume
metadata:
  name: demopv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  azureFile:
    secretName: pv-pvc-demo-secret
    shareName: pv-pvc-demo
    readOnly: false
  persistentVolumeReclaimPolicy: Retain