apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: demo-custom-metrics-hpa
  namespace: nginx
spec:
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: nginx-deployment
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: Pods
    pods:
      metricName: request_duration_seconds_avg
      targetAverageValue: 500